name: Deploy Containers

# on:
#   workflow_run:
#     workflows: ["Build & Push Docker image to ECR"]
#     types:
#       - completed

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/lightsail/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/lightsail/**'

env:
  # influxDB vars
  TF_VAR_influx_url: ${{ secrets.INFLUX_URL }}
  TF_VAR_influx_token: ${{ secrets.INFLUX_TOKEN }}
  TF_VAR_influx_org: ${{ secrets.INFLUX_ORG }}
  TF_VAR_influx_bucket: ${{ secrets.INFLUX_BUCKET }}

  TF_VAR_influx_admin_user: ${{ secrets.DOCKER_INFLUXDB_INIT_USERNAME }}
  TF_VAR_influx_admin_pass: ${{ secrets.DOCKER_INFLUXDB_INIT_PASSWORD }}

  # octopus energy vars
  TF_VAR_octopus_api_key: ${{ secrets.API_KEY }}
  TF_VAR_octopus_base_uri: ${{ secrets.BASE_URI }}
  TF_VAR_octopus_elec_mpan: ${{ secrets.ELEC_MPAN }}
  TF_VAR_octopus_elec_serial: ${{ secrets.ELEC_SERIAL }}
  TF_VAR_octopus_gas_mprn: ${{ secrets.GAS_MPRN }}
  TF_VAR_octopus_gas_serial: ${{ secrets.GAS_SERIAL }}

jobs:
  deploy-ecr:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only if lint.yml passed

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      working-directory: infra/lightsail
      run: terraform init

    - name: Validate Terraform
      working-directory: infra/lightsail
      run: terraform validate

    - name: Plan Terraform changes
      working-directory: infra/lightsail
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      working-directory: infra/lightsail
      run: terraform apply -auto-approve tfplan