name: Deploy ECR Repository

# on:
#   workflow_run:
#     workflows: ["Lint"]
#     types:
#       - completed

on:
  push:
    branches: [ main ]
    paths:
      - 'infra/core/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infra/core/**'

jobs:
  deploy-ecr:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only if lint.yml passed

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Initialize Terraform
      working-directory: infra/core
      run: terraform init

    - name: Validate Terraform
      working-directory: infra/core
      run: terraform validate

    - name: Plan Terraform changes
      working-directory: infra/core
      run: terraform plan -out=tfplan

    - name: Apply Terraform changes
      working-directory: infra/core
      run: terraform apply -auto-approve tfplan